// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createColumn = `-- name: CreateColumn :one
INSERT INTO board_columns (name, color, position)
VALUES ($1, $2, (SELECT COALESCE(MAX(position),0)+1 FROM board_columns))
RETURNING id, name, color, position, created_at
`

type CreateColumnParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, createColumn, arg.Name, arg.Color)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteColumn = `-- name: DeleteColumn :exec
DELETE FROM board_columns WHERE id = $1
`

func (q *Queries) DeleteColumn(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteColumn, id)
	return err
}

const deleteTaskTags = `-- name: DeleteTaskTags :exec
DELETE FROM task_tags WHERE task_id = $1
`

func (q *Queries) DeleteTaskTags(ctx context.Context, taskID int64) error {
	_, err := q.db.Exec(ctx, deleteTaskTags, taskID)
	return err
}

const listColumns = `-- name: ListColumns :many
SELECT id, name, color, position, created_at FROM board_columns ORDER BY position, id
`

func (q *Queries) ListColumns(ctx context.Context) ([]BoardColumn, error) {
	rows, err := q.db.Query(ctx, listColumns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardColumn
	for rows.Next() {
		var i BoardColumn
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksForBoard = `-- name: ListTasksForBoard :many
SELECT t.id, t.title, t.notes, t.priority, t.deadline,
       t.column_id, t.delegated_to, t.is_recurring, t.created_at,
       p.name AS project_name, p.color AS project_color,
       COALESCE(array_agg(tg.name ORDER BY tg.name) FILTER (WHERE tg.name IS NOT NULL), '{}') AS tags
FROM tasks t
JOIN projects p ON p.id = t.project_id
LEFT JOIN task_tags tt ON tt.task_id = t.id
LEFT JOIN tags tg ON tg.id = tt.tag_id
WHERE t.done_at IS NULL
GROUP BY t.id, p.name, p.color
ORDER BY t.priority, t.deadline NULLS LAST, t.created_at
`

type ListTasksForBoardRow struct {
	ID           int64              `json:"id"`
	Title        string             `json:"title"`
	Notes        *string            `json:"notes"`
	Priority     int16              `json:"priority"`
	Deadline     pgtype.Timestamptz `json:"deadline"`
	ColumnID     int64              `json:"column_id"`
	DelegatedTo  *string            `json:"delegated_to"`
	IsRecurring  bool               `json:"is_recurring"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ProjectName  string             `json:"project_name"`
	ProjectColor string             `json:"project_color"`
	Tags         interface{}        `json:"tags"`
}

func (q *Queries) ListTasksForBoard(ctx context.Context) ([]ListTasksForBoardRow, error) {
	rows, err := q.db.Query(ctx, listTasksForBoard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksForBoardRow
	for rows.Next() {
		var i ListTasksForBoardRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Priority,
			&i.Deadline,
			&i.ColumnID,
			&i.DelegatedTo,
			&i.IsRecurring,
			&i.CreatedAt,
			&i.ProjectName,
			&i.ProjectColor,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTaskToColumn = `-- name: MoveTaskToColumn :exec
UPDATE tasks SET column_id = $2 WHERE id = $1
`

type MoveTaskToColumnParams struct {
	ID       int64 `json:"id"`
	ColumnID int64 `json:"column_id"`
}

func (q *Queries) MoveTaskToColumn(ctx context.Context, arg MoveTaskToColumnParams) error {
	_, err := q.db.Exec(ctx, moveTaskToColumn, arg.ID, arg.ColumnID)
	return err
}

const reorderColumns = `-- name: ReorderColumns :exec
UPDATE board_columns SET position = $2 WHERE id = $1
`

type ReorderColumnsParams struct {
	ID       int64 `json:"id"`
	Position int32 `json:"position"`
}

func (q *Queries) ReorderColumns(ctx context.Context, arg ReorderColumnsParams) error {
	_, err := q.db.Exec(ctx, reorderColumns, arg.ID, arg.Position)
	return err
}

const updateColumn = `-- name: UpdateColumn :exec
UPDATE board_columns SET name = $2, color = $3 WHERE id = $1
`

type UpdateColumnParams struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color"`
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) error {
	_, err := q.db.Exec(ctx, updateColumn, arg.ID, arg.Name, arg.Color)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks SET title = $2, notes = $3, priority = $4, deadline = $5 WHERE id = $1
`

type UpdateTaskParams struct {
	ID       int64              `json:"id"`
	Title    string             `json:"title"`
	Notes    *string            `json:"notes"`
	Priority int16              `json:"priority"`
	Deadline pgtype.Timestamptz `json:"deadline"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Notes,
		arg.Priority,
		arg.Deadline,
	)
	return err
}
