// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeTaskForUser = `-- name: CompleteTaskForUser :exec
UPDATE tasks SET
    column_id = (SELECT bc.id FROM board_columns bc WHERE bc.user_id = $2 AND bc.system_kind = 'done'),
    done_at = COALESCE(tasks.done_at, NOW())
WHERE tasks.id = $1 AND tasks.user_id = $2
`

type CompleteTaskForUserParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) CompleteTaskForUser(ctx context.Context, arg CompleteTaskForUserParams) error {
	_, err := q.db.Exec(ctx, completeTaskForUser, arg.ID, arg.UserID)
	return err
}

const createColumn = `-- name: CreateColumn :one
INSERT INTO board_columns (name, color, position, user_id)
VALUES ($1, $2, (SELECT COALESCE(MAX(position),0)+1 FROM board_columns WHERE user_id = $3), $3)
RETURNING id, name, color, position, created_at, user_id, system_kind
`

type CreateColumnParams struct {
	Name   string `json:"name"`
	Color  string `json:"color"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, createColumn, arg.Name, arg.Color, arg.UserID)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UserID,
		&i.SystemKind,
	)
	return i, err
}

const deleteColumn = `-- name: DeleteColumn :exec
DELETE FROM board_columns WHERE id = $1 AND user_id = $2 AND system_kind IS NULL
`

type DeleteColumnParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) DeleteColumn(ctx context.Context, arg DeleteColumnParams) error {
	_, err := q.db.Exec(ctx, deleteColumn, arg.ID, arg.UserID)
	return err
}

const deleteTaskTags = `-- name: DeleteTaskTags :exec
DELETE FROM task_tags WHERE task_id = $1
`

func (q *Queries) DeleteTaskTags(ctx context.Context, taskID int64) error {
	_, err := q.db.Exec(ctx, deleteTaskTags, taskID)
	return err
}

const ensureDoneColumn = `-- name: EnsureDoneColumn :one
INSERT INTO board_columns (name, color, position, user_id, system_kind)
VALUES ('✅ Done', '#4ade80',
        (SELECT COALESCE(MAX(position),0)+1 FROM board_columns WHERE user_id = $1),
        $1, 'done')
ON CONFLICT (user_id, system_kind) WHERE system_kind IS NOT NULL
DO UPDATE SET name = board_columns.name
RETURNING id, name, color, position, created_at, user_id, system_kind
`

func (q *Queries) EnsureDoneColumn(ctx context.Context, userID *int64) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, ensureDoneColumn, userID)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UserID,
		&i.SystemKind,
	)
	return i, err
}

const ensureTodoColumn = `-- name: EnsureTodoColumn :one
INSERT INTO board_columns (name, color, position, user_id, system_kind)
VALUES ('📥 TO DO', '#60a5fa', 0, $1, 'todo')
ON CONFLICT (user_id, system_kind) WHERE system_kind IS NOT NULL
DO UPDATE SET name = board_columns.name
RETURNING id, name, color, position, created_at, user_id, system_kind
`

func (q *Queries) EnsureTodoColumn(ctx context.Context, userID *int64) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, ensureTodoColumn, userID)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UserID,
		&i.SystemKind,
	)
	return i, err
}

const getDoneColumn = `-- name: GetDoneColumn :one
SELECT id, name, color, position, created_at, user_id, system_kind FROM board_columns WHERE user_id = $1 AND system_kind = 'done' LIMIT 1
`

func (q *Queries) GetDoneColumn(ctx context.Context, userID *int64) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, getDoneColumn, userID)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UserID,
		&i.SystemKind,
	)
	return i, err
}

const getTodoColumn = `-- name: GetTodoColumn :one
SELECT id, name, color, position, created_at, user_id, system_kind FROM board_columns WHERE user_id = $1 AND system_kind = 'todo' LIMIT 1
`

func (q *Queries) GetTodoColumn(ctx context.Context, userID *int64) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, getTodoColumn, userID)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UserID,
		&i.SystemKind,
	)
	return i, err
}

const listColumns = `-- name: ListColumns :many
SELECT id, name, color, position, created_at, user_id, system_kind FROM board_columns WHERE user_id = $1 ORDER BY position, id
`

func (q *Queries) ListColumns(ctx context.Context, userID *int64) ([]BoardColumn, error) {
	rows, err := q.db.Query(ctx, listColumns, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardColumn
	for rows.Next() {
		var i BoardColumn
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.CreatedAt,
			&i.UserID,
			&i.SystemKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksForBoard = `-- name: ListTasksForBoard :many
SELECT t.id, t.title, t.notes, t.priority, t.deadline,
       t.column_id, t.delegated_to, t.is_recurring, t.created_at, t.done_at,
       p.name AS project_name, p.color AS project_color,
       COALESCE(array_agg(tg.name ORDER BY tg.name) FILTER (WHERE tg.name IS NOT NULL), '{}') AS tags
FROM tasks t
JOIN projects p ON p.id = t.project_id
LEFT JOIN task_tags tt ON tt.task_id = t.id
LEFT JOIN tags tg ON tg.id = tt.tag_id
WHERE t.user_id = $1
GROUP BY t.id, p.name, p.color
ORDER BY t.priority, t.deadline NULLS LAST, t.created_at
`

type ListTasksForBoardRow struct {
	ID           int64              `json:"id"`
	Title        string             `json:"title"`
	Notes        *string            `json:"notes"`
	Priority     int16              `json:"priority"`
	Deadline     pgtype.Timestamptz `json:"deadline"`
	ColumnID     int64              `json:"column_id"`
	DelegatedTo  *string            `json:"delegated_to"`
	IsRecurring  bool               `json:"is_recurring"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DoneAt       pgtype.Timestamptz `json:"done_at"`
	ProjectName  string             `json:"project_name"`
	ProjectColor string             `json:"project_color"`
	Tags         interface{}        `json:"tags"`
}

func (q *Queries) ListTasksForBoard(ctx context.Context, userID *int64) ([]ListTasksForBoardRow, error) {
	rows, err := q.db.Query(ctx, listTasksForBoard, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksForBoardRow
	for rows.Next() {
		var i ListTasksForBoardRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Priority,
			&i.Deadline,
			&i.ColumnID,
			&i.DelegatedTo,
			&i.IsRecurring,
			&i.CreatedAt,
			&i.DoneAt,
			&i.ProjectName,
			&i.ProjectColor,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveOrphanTasksToColumn = `-- name: MoveOrphanTasksToColumn :exec
UPDATE tasks SET column_id = $1 WHERE user_id = $2 AND column_id IS NULL
`

type MoveOrphanTasksToColumnParams struct {
	ColumnID int64  `json:"column_id"`
	UserID   *int64 `json:"user_id"`
}

func (q *Queries) MoveOrphanTasksToColumn(ctx context.Context, arg MoveOrphanTasksToColumnParams) error {
	_, err := q.db.Exec(ctx, moveOrphanTasksToColumn, arg.ColumnID, arg.UserID)
	return err
}

const moveTaskToColumn = `-- name: MoveTaskToColumn :exec
UPDATE tasks SET
    column_id = $2,
    done_at = CASE
        WHEN $2 = (SELECT bc.id FROM board_columns bc WHERE bc.user_id = $3 AND bc.system_kind = 'done')
            THEN COALESCE(tasks.done_at, NOW())
        ELSE NULL
    END
WHERE tasks.id = $1 AND tasks.user_id = $3
`

type MoveTaskToColumnParams struct {
	ID       int64  `json:"id"`
	ColumnID int64  `json:"column_id"`
	UserID   *int64 `json:"user_id"`
}

func (q *Queries) MoveTaskToColumn(ctx context.Context, arg MoveTaskToColumnParams) error {
	_, err := q.db.Exec(ctx, moveTaskToColumn, arg.ID, arg.ColumnID, arg.UserID)
	return err
}

const reorderColumns = `-- name: ReorderColumns :exec
UPDATE board_columns SET position = $2 WHERE id = $1 AND user_id = $3
`

type ReorderColumnsParams struct {
	ID       int64  `json:"id"`
	Position int32  `json:"position"`
	UserID   *int64 `json:"user_id"`
}

func (q *Queries) ReorderColumns(ctx context.Context, arg ReorderColumnsParams) error {
	_, err := q.db.Exec(ctx, reorderColumns, arg.ID, arg.Position, arg.UserID)
	return err
}

const updateColumn = `-- name: UpdateColumn :exec
UPDATE board_columns SET name = $2, color = $3 WHERE id = $1 AND user_id = $4
`

type UpdateColumnParams struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Color  string `json:"color"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) error {
	_, err := q.db.Exec(ctx, updateColumn,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.UserID,
	)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks SET title = $2, notes = $3, priority = $4, deadline = $5 WHERE id = $1 AND user_id = $6
`

type UpdateTaskParams struct {
	ID       int64              `json:"id"`
	Title    string             `json:"title"`
	Notes    *string            `json:"notes"`
	Priority int16              `json:"priority"`
	Deadline pgtype.Timestamptz `json:"deadline"`
	UserID   *int64             `json:"user_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Notes,
		arg.Priority,
		arg.Deadline,
		arg.UserID,
	)
	return err
}
