// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTaskByID = `-- name: GetTaskByID :one
SELECT t.id, t.title, t.notes, t.priority, t.deadline, t.status,
       t.delegated_to, t.is_recurring, t.created_at,
       p.name AS project_name, p.color AS project_color
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.id = $1
`

type GetTaskByIDRow struct {
	ID           int64              `json:"id"`
	Title        string             `json:"title"`
	Notes        *string            `json:"notes"`
	Priority     int16              `json:"priority"`
	Deadline     pgtype.Timestamptz `json:"deadline"`
	Status       string             `json:"status"`
	DelegatedTo  *string            `json:"delegated_to"`
	IsRecurring  bool               `json:"is_recurring"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ProjectName  string             `json:"project_name"`
	ProjectColor string             `json:"project_color"`
}

func (q *Queries) GetTaskByID(ctx context.Context, id int64) (GetTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Deadline,
		&i.Status,
		&i.DelegatedTo,
		&i.IsRecurring,
		&i.CreatedAt,
		&i.ProjectName,
		&i.ProjectColor,
	)
	return i, err
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT t.id, t.title, t.notes, t.priority, t.deadline, t.status,
       t.delegated_to, t.is_recurring, t.created_at,
       p.name AS project_name, p.color AS project_color
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.done_at IS NULL
ORDER BY t.priority, t.deadline NULLS LAST, t.created_at
`

type ListTasksByStatusRow struct {
	ID           int64              `json:"id"`
	Title        string             `json:"title"`
	Notes        *string            `json:"notes"`
	Priority     int16              `json:"priority"`
	Deadline     pgtype.Timestamptz `json:"deadline"`
	Status       string             `json:"status"`
	DelegatedTo  *string            `json:"delegated_to"`
	IsRecurring  bool               `json:"is_recurring"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ProjectName  string             `json:"project_name"`
	ProjectColor string             `json:"project_color"`
}

func (q *Queries) ListTasksByStatus(ctx context.Context) ([]ListTasksByStatusRow, error) {
	rows, err := q.db.Query(ctx, listTasksByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByStatusRow
	for rows.Next() {
		var i ListTasksByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Priority,
			&i.Deadline,
			&i.Status,
			&i.DelegatedTo,
			&i.IsRecurring,
			&i.CreatedAt,
			&i.ProjectName,
			&i.ProjectColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET status = $2 WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status)
	return err
}
