// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOrphanData = `-- name: ClaimOrphanData :exec
UPDATE board_columns SET user_id = $1 WHERE user_id IS NULL
`

func (q *Queries) ClaimOrphanData(ctx context.Context, userID *int64) error {
	_, err := q.db.Exec(ctx, claimOrphanData, userID)
	return err
}

const claimOrphanTasks = `-- name: ClaimOrphanTasks :exec
UPDATE tasks SET user_id = $1 WHERE user_id IS NULL
`

func (q *Queries) ClaimOrphanTasks(ctx context.Context, userID *int64) error {
	_, err := q.db.Exec(ctx, claimOrphanTasks, userID)
	return err
}

const cleanExpiredSessions = `-- name: CleanExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) CleanExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanExpiredSessions)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getSession = `-- name: GetSession :one
SELECT s.token, s.user_id, s.expires_at, s.created_at, u.email, u.name, u.avatar, u.telegram_id IS NOT NULL AS telegram_linked
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = $1 AND s.expires_at > NOW()
`

type GetSessionRow struct {
	Token          string             `json:"token"`
	UserID         int64              `json:"user_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	Avatar         *string            `json:"avatar"`
	TelegramLinked interface{}        `json:"telegram_linked"`
}

func (q *Queries) GetSession(ctx context.Context, token string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, token)
	var i GetSessionRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
		&i.Avatar,
		&i.TelegramLinked,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (google_id, email, name, avatar)
VALUES ($1, $2, $3, $4)
ON CONFLICT (google_id) DO UPDATE
    SET email  = EXCLUDED.email,
        name   = EXCLUDED.name,
        avatar = EXCLUDED.avatar
RETURNING id, google_id, email, name, avatar, created_at, telegram_id
`

type UpsertUserParams struct {
	GoogleID string  `json:"google_id"`
	Email    string  `json:"email"`
	Name     string  `json:"name"`
	Avatar   *string `json:"avatar"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Avatar,
		&i.CreatedAt,
		&i.TelegramID,
	)
	return i, err
}
