// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimTasksByTelegram = `-- name: ClaimTasksByTelegram :exec
UPDATE tasks SET user_id = $1
WHERE telegram_user_id = $2 AND user_id IS NULL
`

type ClaimTasksByTelegramParams struct {
	UserID         *int64 `json:"user_id"`
	TelegramUserID *int64 `json:"telegram_user_id"`
}

func (q *Queries) ClaimTasksByTelegram(ctx context.Context, arg ClaimTasksByTelegramParams) error {
	_, err := q.db.Exec(ctx, claimTasksByTelegram, arg.UserID, arg.TelegramUserID)
	return err
}

const createLinkToken = `-- name: CreateLinkToken :one
INSERT INTO link_tokens (token, user_id)
VALUES ($1, $2)
RETURNING token, user_id, expires_at, created_at
`

type CreateLinkTokenParams struct {
	Token  string `json:"token"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) CreateLinkToken(ctx context.Context, arg CreateLinkTokenParams) (LinkToken, error) {
	row := q.db.QueryRow(ctx, createLinkToken, arg.Token, arg.UserID)
	var i LinkToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLinkToken = `-- name: DeleteLinkToken :exec
DELETE FROM link_tokens WHERE token = $1
`

func (q *Queries) DeleteLinkToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteLinkToken, token)
	return err
}

const getLinkToken = `-- name: GetLinkToken :one
SELECT lt.token, lt.user_id, lt.expires_at, lt.created_at, u.email, u.name
FROM link_tokens lt
JOIN users u ON u.id = lt.user_id
WHERE lt.token = $1 AND lt.expires_at > NOW()
`

type GetLinkTokenRow struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
}

func (q *Queries) GetLinkToken(ctx context.Context, token string) (GetLinkTokenRow, error) {
	row := q.db.QueryRow(ctx, getLinkToken, token)
	var i GetLinkTokenRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, google_id, email, name, avatar, created_at, telegram_id FROM users WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID *int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Avatar,
		&i.CreatedAt,
		&i.TelegramID,
	)
	return i, err
}

const setUserTelegramID = `-- name: SetUserTelegramID :exec
UPDATE users SET telegram_id = $2 WHERE id = $1
`

type SetUserTelegramIDParams struct {
	ID         int64  `json:"id"`
	TelegramID *int64 `json:"telegram_id"`
}

func (q *Queries) SetUserTelegramID(ctx context.Context, arg SetUserTelegramIDParams) error {
	_, err := q.db.Exec(ctx, setUserTelegramID, arg.ID, arg.TelegramID)
	return err
}
