// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BoardColumn struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	Color      string             `json:"color"`
	Position   int32              `json:"position"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UserID     *int64             `json:"user_id"`
	SystemKind *string            `json:"system_kind"`
}

type LinkToken struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Reminder struct {
	ID       int64              `json:"id"`
	TaskID   int64              `json:"task_id"`
	RemindAt pgtype.Timestamptz `json:"remind_at"`
	Sent     bool               `json:"sent"`
}

type Session struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Task struct {
	ID             int64              `json:"id"`
	ProjectID      int64              `json:"project_id"`
	Title          string             `json:"title"`
	Notes          *string            `json:"notes"`
	Priority       int16              `json:"priority"`
	Deadline       pgtype.Timestamptz `json:"deadline"`
	DoneAt         pgtype.Timestamptz `json:"done_at"`
	DelegatedTo    *string            `json:"delegated_to"`
	IsRecurring    bool               `json:"is_recurring"`
	RecurRule      *string            `json:"recur_rule"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ColumnID       int64              `json:"column_id"`
	UserID         *int64             `json:"user_id"`
	TelegramUserID *int64             `json:"telegram_user_id"`
}

type TaskTag struct {
	TaskID int64 `json:"task_id"`
	TagID  int64 `json:"tag_id"`
}

type User struct {
	ID         int64              `json:"id"`
	GoogleID   string             `json:"google_id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	Avatar     *string            `json:"avatar"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TelegramID *int64             `json:"telegram_id"`
}
