// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReminder = `-- name: CreateReminder :one
INSERT INTO reminders (task_id, remind_at)
VALUES ($1, $2)
RETURNING id, task_id, remind_at, sent
`

type CreateReminderParams struct {
	TaskID   int64              `json:"task_id"`
	RemindAt pgtype.Timestamptz `json:"remind_at"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, createReminder, arg.TaskID, arg.RemindAt)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.RemindAt,
		&i.Sent,
	)
	return i, err
}

const listDueReminders = `-- name: ListDueReminders :many
SELECT r.id, r.task_id, r.remind_at, r.sent, t.title AS task_title, t.deadline AS task_deadline
FROM reminders r
JOIN tasks t ON t.id = r.task_id
WHERE r.sent = FALSE AND r.remind_at <= NOW()
`

type ListDueRemindersRow struct {
	ID           int64              `json:"id"`
	TaskID       int64              `json:"task_id"`
	RemindAt     pgtype.Timestamptz `json:"remind_at"`
	Sent         bool               `json:"sent"`
	TaskTitle    string             `json:"task_title"`
	TaskDeadline pgtype.Timestamptz `json:"task_deadline"`
}

func (q *Queries) ListDueReminders(ctx context.Context) ([]ListDueRemindersRow, error) {
	rows, err := q.db.Query(ctx, listDueReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueRemindersRow
	for rows.Next() {
		var i ListDueRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.RemindAt,
			&i.Sent,
			&i.TaskTitle,
			&i.TaskDeadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderSent = `-- name: MarkReminderSent :exec
UPDATE reminders SET sent = TRUE WHERE id = $1
`

func (q *Queries) MarkReminderSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markReminderSent, id)
	return err
}
