// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
)

const attachTag = `-- name: AttachTag :exec
INSERT INTO task_tags (task_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AttachTagParams struct {
	TaskID int64 `json:"task_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) AttachTag(ctx context.Context, arg AttachTagParams) error {
	_, err := q.db.Exec(ctx, attachTag, arg.TaskID, arg.TagID)
	return err
}

const getTaskTags = `-- name: GetTaskTags :many
SELECT tg.name FROM tags tg
JOIN task_tags tt ON tt.tag_id = tg.id
WHERE tt.task_id = $1
`

func (q *Queries) GetTaskTags(ctx context.Context, taskID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getTaskTags, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
