// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeTask = `-- name: CompleteTask :exec
UPDATE tasks SET done_at = NOW() WHERE id = $1
`

func (q *Queries) CompleteTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeTask, id)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, notes, priority, deadline, delegated_to, is_recurring, recur_rule)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, title, notes, priority, deadline, done_at, delegated_to, is_recurring, recur_rule, created_at
`

type CreateTaskParams struct {
	ProjectID   int64              `json:"project_id"`
	Title       string             `json:"title"`
	Notes       *string            `json:"notes"`
	Priority    int16              `json:"priority"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
	DelegatedTo *string            `json:"delegated_to"`
	IsRecurring bool               `json:"is_recurring"`
	RecurRule   *string            `json:"recur_rule"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Notes,
		arg.Priority,
		arg.Deadline,
		arg.DelegatedTo,
		arg.IsRecurring,
		arg.RecurRule,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Deadline,
		&i.DoneAt,
		&i.DelegatedTo,
		&i.IsRecurring,
		&i.RecurRule,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT t.id, t.project_id, t.title, t.notes, t.priority, t.deadline, t.done_at, t.delegated_to, t.is_recurring, t.recur_rule, t.created_at, p.name AS project_name
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.id = $1
`

type GetTaskRow struct {
	ID          int64              `json:"id"`
	ProjectID   int64              `json:"project_id"`
	Title       string             `json:"title"`
	Notes       *string            `json:"notes"`
	Priority    int16              `json:"priority"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
	DoneAt      pgtype.Timestamptz `json:"done_at"`
	DelegatedTo *string            `json:"delegated_to"`
	IsRecurring bool               `json:"is_recurring"`
	RecurRule   *string            `json:"recur_rule"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProjectName string             `json:"project_name"`
}

func (q *Queries) GetTask(ctx context.Context, id int64) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Deadline,
		&i.DoneAt,
		&i.DelegatedTo,
		&i.IsRecurring,
		&i.RecurRule,
		&i.CreatedAt,
		&i.ProjectName,
	)
	return i, err
}

const listOpenTasks = `-- name: ListOpenTasks :many
SELECT t.id, t.project_id, t.title, t.notes, t.priority, t.deadline, t.done_at, t.delegated_to, t.is_recurring, t.recur_rule, t.created_at, p.name AS project_name
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.done_at IS NULL
ORDER BY t.priority, t.deadline NULLS LAST, t.created_at
`

type ListOpenTasksRow struct {
	ID          int64              `json:"id"`
	ProjectID   int64              `json:"project_id"`
	Title       string             `json:"title"`
	Notes       *string            `json:"notes"`
	Priority    int16              `json:"priority"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
	DoneAt      pgtype.Timestamptz `json:"done_at"`
	DelegatedTo *string            `json:"delegated_to"`
	IsRecurring bool               `json:"is_recurring"`
	RecurRule   *string            `json:"recur_rule"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProjectName string             `json:"project_name"`
}

func (q *Queries) ListOpenTasks(ctx context.Context) ([]ListOpenTasksRow, error) {
	rows, err := q.db.Query(ctx, listOpenTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenTasksRow
	for rows.Next() {
		var i ListOpenTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Notes,
			&i.Priority,
			&i.Deadline,
			&i.DoneAt,
			&i.DelegatedTo,
			&i.IsRecurring,
			&i.RecurRule,
			&i.CreatedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueTasks = `-- name: ListOverdueTasks :many
SELECT t.id, t.project_id, t.title, t.notes, t.priority, t.deadline, t.done_at, t.delegated_to, t.is_recurring, t.recur_rule, t.created_at, p.name AS project_name
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.done_at IS NULL
  AND t.deadline < NOW()
ORDER BY t.deadline
`

type ListOverdueTasksRow struct {
	ID          int64              `json:"id"`
	ProjectID   int64              `json:"project_id"`
	Title       string             `json:"title"`
	Notes       *string            `json:"notes"`
	Priority    int16              `json:"priority"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
	DoneAt      pgtype.Timestamptz `json:"done_at"`
	DelegatedTo *string            `json:"delegated_to"`
	IsRecurring bool               `json:"is_recurring"`
	RecurRule   *string            `json:"recur_rule"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProjectName string             `json:"project_name"`
}

func (q *Queries) ListOverdueTasks(ctx context.Context) ([]ListOverdueTasksRow, error) {
	rows, err := q.db.Query(ctx, listOverdueTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverdueTasksRow
	for rows.Next() {
		var i ListOverdueTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Notes,
			&i.Priority,
			&i.Deadline,
			&i.DoneAt,
			&i.DelegatedTo,
			&i.IsRecurring,
			&i.RecurRule,
			&i.CreatedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, color, created_at FROM projects ORDER BY id
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodayTasks = `-- name: ListTodayTasks :many
SELECT t.id, t.project_id, t.title, t.notes, t.priority, t.deadline, t.done_at, t.delegated_to, t.is_recurring, t.recur_rule, t.created_at, p.name AS project_name
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.done_at IS NULL
  AND t.deadline < NOW() + INTERVAL '24 hours'
ORDER BY t.deadline NULLS LAST
`

type ListTodayTasksRow struct {
	ID          int64              `json:"id"`
	ProjectID   int64              `json:"project_id"`
	Title       string             `json:"title"`
	Notes       *string            `json:"notes"`
	Priority    int16              `json:"priority"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
	DoneAt      pgtype.Timestamptz `json:"done_at"`
	DelegatedTo *string            `json:"delegated_to"`
	IsRecurring bool               `json:"is_recurring"`
	RecurRule   *string            `json:"recur_rule"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProjectName string             `json:"project_name"`
}

func (q *Queries) ListTodayTasks(ctx context.Context) ([]ListTodayTasksRow, error) {
	rows, err := q.db.Query(ctx, listTodayTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodayTasksRow
	for rows.Next() {
		var i ListTodayTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Notes,
			&i.Priority,
			&i.Deadline,
			&i.DoneAt,
			&i.DelegatedTo,
			&i.IsRecurring,
			&i.RecurRule,
			&i.CreatedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
