// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeOrphanTaskForTelegram = `-- name: CompleteOrphanTaskForTelegram :execrows
UPDATE tasks SET done_at = NOW()
WHERE id = $1
  AND user_id IS NULL
  AND telegram_user_id = $2
  AND done_at IS NULL
`

type CompleteOrphanTaskForTelegramParams struct {
	ID             int64 `json:"id"`
	TelegramUserID int64 `json:"telegram_user_id"`
}

func (q *Queries) CompleteOrphanTaskForTelegram(ctx context.Context, arg CompleteOrphanTaskForTelegramParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeOrphanTaskForTelegram, arg.ID, arg.TelegramUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, notes, priority, deadline, delegated_to, is_recurring, recur_rule, user_id, telegram_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, project_id, title, notes, priority, deadline, done_at, delegated_to, is_recurring, recur_rule, created_at, column_id, user_id, telegram_user_id
`

type CreateTaskParams struct {
	ProjectID      int64              `json:"project_id"`
	Title          string             `json:"title"`
	Notes          *string            `json:"notes"`
	Priority       int16              `json:"priority"`
	Deadline       pgtype.Timestamptz `json:"deadline"`
	DelegatedTo    *string            `json:"delegated_to"`
	IsRecurring    bool               `json:"is_recurring"`
	RecurRule      *string            `json:"recur_rule"`
	UserID         *int64             `json:"user_id"`
	TelegramUserID *int64             `json:"telegram_user_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Notes,
		arg.Priority,
		arg.Deadline,
		arg.DelegatedTo,
		arg.IsRecurring,
		arg.RecurRule,
		arg.UserID,
		arg.TelegramUserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Deadline,
		&i.DoneAt,
		&i.DelegatedTo,
		&i.IsRecurring,
		&i.RecurRule,
		&i.CreatedAt,
		&i.ColumnID,
		&i.UserID,
		&i.TelegramUserID,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1 AND (user_id = $2 OR user_id IS NULL)
`

type DeleteTaskParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.UserID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT t.id, t.project_id, t.title, t.notes, t.priority, t.deadline, t.done_at, t.delegated_to, t.is_recurring, t.recur_rule, t.created_at, t.column_id, t.user_id, t.telegram_user_id, p.name AS project_name
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.id = $1
`

type GetTaskRow struct {
	ID             int64              `json:"id"`
	ProjectID      int64              `json:"project_id"`
	Title          string             `json:"title"`
	Notes          *string            `json:"notes"`
	Priority       int16              `json:"priority"`
	Deadline       pgtype.Timestamptz `json:"deadline"`
	DoneAt         pgtype.Timestamptz `json:"done_at"`
	DelegatedTo    *string            `json:"delegated_to"`
	IsRecurring    bool               `json:"is_recurring"`
	RecurRule      *string            `json:"recur_rule"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ColumnID       int64              `json:"column_id"`
	UserID         *int64             `json:"user_id"`
	TelegramUserID *int64             `json:"telegram_user_id"`
	ProjectName    string             `json:"project_name"`
}

func (q *Queries) GetTask(ctx context.Context, id int64) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Deadline,
		&i.DoneAt,
		&i.DelegatedTo,
		&i.IsRecurring,
		&i.RecurRule,
		&i.CreatedAt,
		&i.ColumnID,
		&i.UserID,
		&i.TelegramUserID,
		&i.ProjectName,
	)
	return i, err
}

const listOpenTasksForTelegram = `-- name: ListOpenTasksForTelegram :many
SELECT t.id, t.project_id, t.title, t.notes, t.priority, t.deadline, t.done_at, t.delegated_to, t.is_recurring, t.recur_rule, t.created_at, t.column_id, t.user_id, t.telegram_user_id, p.name AS project_name
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.done_at IS NULL
  AND (
        ($1::bigint IS NOT NULL AND t.user_id = $1)
     OR (t.user_id IS NULL AND t.telegram_user_id = $2)
  )
ORDER BY t.priority, t.deadline NULLS LAST, t.created_at
`

type ListOpenTasksForTelegramParams struct {
	UserID         *int64 `json:"user_id"`
	TelegramUserID int64  `json:"telegram_user_id"`
}

type ListOpenTasksForTelegramRow struct {
	ID             int64              `json:"id"`
	ProjectID      int64              `json:"project_id"`
	Title          string             `json:"title"`
	Notes          *string            `json:"notes"`
	Priority       int16              `json:"priority"`
	Deadline       pgtype.Timestamptz `json:"deadline"`
	DoneAt         pgtype.Timestamptz `json:"done_at"`
	DelegatedTo    *string            `json:"delegated_to"`
	IsRecurring    bool               `json:"is_recurring"`
	RecurRule      *string            `json:"recur_rule"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ColumnID       int64              `json:"column_id"`
	UserID         *int64             `json:"user_id"`
	TelegramUserID *int64             `json:"telegram_user_id"`
	ProjectName    string             `json:"project_name"`
}

func (q *Queries) ListOpenTasksForTelegram(ctx context.Context, arg ListOpenTasksForTelegramParams) ([]ListOpenTasksForTelegramRow, error) {
	rows, err := q.db.Query(ctx, listOpenTasksForTelegram, arg.UserID, arg.TelegramUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenTasksForTelegramRow
	for rows.Next() {
		var i ListOpenTasksForTelegramRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Notes,
			&i.Priority,
			&i.Deadline,
			&i.DoneAt,
			&i.DelegatedTo,
			&i.IsRecurring,
			&i.RecurRule,
			&i.CreatedAt,
			&i.ColumnID,
			&i.UserID,
			&i.TelegramUserID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueTasksForTelegram = `-- name: ListOverdueTasksForTelegram :many
SELECT t.id, t.project_id, t.title, t.notes, t.priority, t.deadline, t.done_at, t.delegated_to, t.is_recurring, t.recur_rule, t.created_at, t.column_id, t.user_id, t.telegram_user_id, p.name AS project_name
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.done_at IS NULL
  AND t.deadline < NOW()
  AND (
        ($1::bigint IS NOT NULL AND t.user_id = $1)
     OR (t.user_id IS NULL AND t.telegram_user_id = $2)
  )
ORDER BY t.deadline
`

type ListOverdueTasksForTelegramParams struct {
	UserID         *int64 `json:"user_id"`
	TelegramUserID int64  `json:"telegram_user_id"`
}

type ListOverdueTasksForTelegramRow struct {
	ID             int64              `json:"id"`
	ProjectID      int64              `json:"project_id"`
	Title          string             `json:"title"`
	Notes          *string            `json:"notes"`
	Priority       int16              `json:"priority"`
	Deadline       pgtype.Timestamptz `json:"deadline"`
	DoneAt         pgtype.Timestamptz `json:"done_at"`
	DelegatedTo    *string            `json:"delegated_to"`
	IsRecurring    bool               `json:"is_recurring"`
	RecurRule      *string            `json:"recur_rule"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ColumnID       int64              `json:"column_id"`
	UserID         *int64             `json:"user_id"`
	TelegramUserID *int64             `json:"telegram_user_id"`
	ProjectName    string             `json:"project_name"`
}

func (q *Queries) ListOverdueTasksForTelegram(ctx context.Context, arg ListOverdueTasksForTelegramParams) ([]ListOverdueTasksForTelegramRow, error) {
	rows, err := q.db.Query(ctx, listOverdueTasksForTelegram, arg.UserID, arg.TelegramUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverdueTasksForTelegramRow
	for rows.Next() {
		var i ListOverdueTasksForTelegramRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Notes,
			&i.Priority,
			&i.Deadline,
			&i.DoneAt,
			&i.DelegatedTo,
			&i.IsRecurring,
			&i.RecurRule,
			&i.CreatedAt,
			&i.ColumnID,
			&i.UserID,
			&i.TelegramUserID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, color, created_at FROM projects ORDER BY id
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodayTasksForTelegram = `-- name: ListTodayTasksForTelegram :many
SELECT t.id, t.project_id, t.title, t.notes, t.priority, t.deadline, t.done_at, t.delegated_to, t.is_recurring, t.recur_rule, t.created_at, t.column_id, t.user_id, t.telegram_user_id, p.name AS project_name
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.done_at IS NULL
  AND t.deadline < NOW() + INTERVAL '24 hours'
  AND (
        ($1::bigint IS NOT NULL AND t.user_id = $1)
     OR (t.user_id IS NULL AND t.telegram_user_id = $2)
  )
ORDER BY t.deadline NULLS LAST
`

type ListTodayTasksForTelegramParams struct {
	UserID         *int64 `json:"user_id"`
	TelegramUserID int64  `json:"telegram_user_id"`
}

type ListTodayTasksForTelegramRow struct {
	ID             int64              `json:"id"`
	ProjectID      int64              `json:"project_id"`
	Title          string             `json:"title"`
	Notes          *string            `json:"notes"`
	Priority       int16              `json:"priority"`
	Deadline       pgtype.Timestamptz `json:"deadline"`
	DoneAt         pgtype.Timestamptz `json:"done_at"`
	DelegatedTo    *string            `json:"delegated_to"`
	IsRecurring    bool               `json:"is_recurring"`
	RecurRule      *string            `json:"recur_rule"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ColumnID       int64              `json:"column_id"`
	UserID         *int64             `json:"user_id"`
	TelegramUserID *int64             `json:"telegram_user_id"`
	ProjectName    string             `json:"project_name"`
}

func (q *Queries) ListTodayTasksForTelegram(ctx context.Context, arg ListTodayTasksForTelegramParams) ([]ListTodayTasksForTelegramRow, error) {
	rows, err := q.db.Query(ctx, listTodayTasksForTelegram, arg.UserID, arg.TelegramUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodayTasksForTelegramRow
	for rows.Next() {
		var i ListTodayTasksForTelegramRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Notes,
			&i.Priority,
			&i.Deadline,
			&i.DoneAt,
			&i.DelegatedTo,
			&i.IsRecurring,
			&i.RecurRule,
			&i.CreatedAt,
			&i.ColumnID,
			&i.UserID,
			&i.TelegramUserID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
